import PARTNERS__INVITRO from './invitro.svg';
import PARTNERS__MNOGOLOSOSYA from './mnogolososya.svg';
import PARTNERS__THE5POST from './the5post.svg';
import PARTNERS__VPROK from './vprok.svg';
import PARTNERS__SBERZVUK from './sberzvook.svg';
import PARTNERS__IVI from './ivi.svg';
import PARTNERS__ALIEXPRESS from './aliExpress.svg';

export const allPartners = {
    PARTNERS__VPROK,
    PARTNERS__INVITRO,
    PARTNERS__MNOGOLOSOSYA,
    PARTNERS__THE5POST,
    PARTNERS__SBERZVUK,
    PARTNERS__IVI,
    PARTNERS__ALIEXPRESS,
    PROFILE_PARTNERS__VPROK: PARTNERS__VPROK,
    PROFILE_PARTNERS__INVITRO: PARTNERS__INVITRO,
    PROFILE_PARTNERS__MNOGOLOSOSYA: PARTNERS__MNOGOLOSOSYA,
    PROFILE_PARTNERS__THE5POST: PARTNERS__THE5POST,
    PROFILE_PARTNERS__SBERZVUK: PARTNERS__SBERZVUK,
    PROFILE_PARTNERS__IVI: PARTNERS__IVI,
    PROFILE_PARTNERS__ALIEXPRESS: PARTNERS__ALIEXPRESS,
};

export default allPartners;
