import CRITICAL_NOTICE from './CRITICAL_NOTICE';
import CRITICAL_NOTICE__PROFILE from './CRITICAL_NOTICE__PROFILE';
import CRITICAL_NOTICE__PROFILE__SUBSCRIBED from './CRITICAL_NOTICE__PROFILE__SUBSCRIBED';
import FEATURES from './FEATURES';
import OFFERS from './OFFERS';
import PARTNERS from './PARTNERS';
import SUBSCRIBE_STEPS from './SUBSCRIBE_STEPS';

export const cardsListTypes = {
    CRITICAL_NOTICE,
    CRITICAL_NOTICE__PROFILE,
    CRITICAL_NOTICE__PROFILE__SUBSCRIBED,
    FEATURES,
    OFFERS,
    PARTNERS,
    SUBSCRIBE_STEPS,
};

export default cardsListTypes;
